name: Lint
on:
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print branch
        run: git branch --show-current
      - name: Clear golangci-lint cache
        run: golangci-lint cache clean
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.3
