name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  test:
    strategy:
      matrix:
        containers: [ 1.24 ]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containers }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Update go modules
        run: go mod tidy
      - name: Unit Tests
        run: go test -v -race -timeout=60s -tags jwx_es256k ./...
