name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  test:
    strategy:
      matrix:
        containers: [ 1.20.4, 1.19, 1.18 ]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containers }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Update go modules
        run: go mod tidy
      - name: Unit Tests
        run: go test -v -race -timeout=60s ./...
